CC = ppc-amigaos-gcc
CXX = ppc-amigaos-g++
CFLAGS = -O2 -Wall -I./include
LDFLAGS = -lauto

DOCKER_IMAGE = walkero/amigagccondocker:os4-gcc11
DOCKER_RUN   = docker run --rm -v "$(shell pwd):/work" -w /work $(DOCKER_IMAGE)

BUILD_DIR = build

# AmiUpdate integration
AMIUPDATE_DIR = ../AmiUpdateIntegration
AMIUPDATE_CONFIG = amiupdate.yml
include $(AMIUPDATE_DIR)/amiupdate.mk
DIST_DIR = dist
DIST_NAME = AmigaDiskBench
TARGET = $(BUILD_DIR)/AmigaDiskBench
SRC = src/main.c src/engine.c src/engine_info.c src/engine_tests.c src/engine_persistence.c src/engine_workloads.c \
      src/engine_system.c src/engine_warmup.c src/engine_utils.c \
      src/workloads/workload_legacy_sprinter.c src/workloads/workload_legacy_heavy.c \
      src/workloads/workload_legacy_legacy.c src/workloads/workload_legacy_grind.c \
      src/workloads/workload_sequential.c src/workloads/workload_random_4k.c \
      src/workloads/workload_profiler.c \
      src/workloads/workload_sequential_read.c src/workloads/workload_random_4k_read.c \
      src/workloads/workload_mixed_rw.c \
      src/gui.c src/gui_details_window.c src/gui_compare_window.c src/gui_describe_window.c src/gui_utils.c src/gui_prefs.c src/gui_history.c src/gui_system.c src/gui_worker.c src/gui_report.c src/gui_layout.c src/gui_events.c src/gui_viz.c src/gui_viz_render.c src/gui_bulk.c src/gui_export.c src/gui_health.c src/gui_info.c src/gui_logging.c src/engine_smart.c src/engine_diskinfo.c src/benchmark_queue.c src/viz_profile.c src/gui_validate.c
OBJ = $(patsubst src/%.c, $(BUILD_DIR)/%.o, $(SRC)) $(AMIUPDATE_OBJ)

.PHONY: all dist dist-lha install clean

all: $(BUILD_DIR) $(TARGET) dist

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET) $(LDFLAGS)

$(BUILD_DIR)/%.o: src/%.c | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(AMIUPDATE_CFLAGS) -c $< -o $@

# Create distribution directory with all files needed to run on AmigaOS 4
dist: $(TARGET)
	@echo "=== Creating distribution ==="
	rm -rf $(DIST_DIR)/
	mkdir -p $(DIST_DIR)/$(DIST_NAME)
	mkdir -p $(DIST_DIR)/$(DIST_NAME)/Visualizations
	@# Drawer icon (shown when browsing the parent directory)
	cp icons/AmigaDiskBench_drawer.info $(DIST_DIR)/$(DIST_NAME).info
	@# Main application binary and icon
	cp $(TARGET) $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench
	cp src/app.info $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench.info
	@# Documentation
	cp AmigaDiskBench.readme $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench.readme
	@# Visualization profiles
	cp Visualizations/*.viz $(DIST_DIR)/$(DIST_NAME)/Visualizations/
	cp Visualizations.info $(DIST_DIR)/$(DIST_NAME)/Visualizations.info
	@# AutoInstall script (generated by AmiUpdate toolkit)
	cp AutoInstall $(DIST_DIR)/$(DIST_NAME)/
	@# Plain-text readme at archive root for os4depot
	cp AmigaDiskBench.readme $(DIST_DIR)/readme.txt
	@echo "Distribution created in $(DIST_DIR)/$(DIST_NAME)/"
	@echo "Contents:"
	@find $(DIST_DIR)/$(DIST_NAME) -type f | sort

# Create LHA archive from distribution
dist-lha: dist
	@echo "=== Creating LHA archive ==="
	$(DOCKER_RUN) sh -c 'cd dist && lha ao5q /work/dist/$(DIST_NAME).lha $(DIST_NAME) readme.txt'
	@ls -la $(DIST_DIR)/$(DIST_NAME).lha
	@echo "Archive created: $(DIST_DIR)/$(DIST_NAME).lha"

install: all
	mkdir -p $(DIST_DIR)/$(DIST_NAME)
	cp icons/AmigaDiskBench_drawer.info $(DIST_DIR)/$(DIST_NAME).info
	cp $(TARGET) $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench
	cp AmigaDiskBench.info $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench.info
	cp AmigaDiskBench.readme $(DIST_DIR)/$(DIST_NAME)/AmigaDiskBench.readme
	cp -r Visualizations $(DIST_DIR)/$(DIST_NAME)/Visualizations
	cp Visualizations.info $(DIST_DIR)/$(DIST_NAME)/Visualizations.info
	@echo "Installation complete to $(DIST_DIR)/$(DIST_NAME)/"

clean: amiupdate-clean
	rm -rf $(BUILD_DIR) $(DIST_DIR)
