/*
 * AmigaDiskBench - A modern benchmark for AmigaOS 4.x
 * Copyright (c) 2026 Team Derfs
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "gui_internal.h"

/**
 * ExportToAnsiText
 *
 * Reads the historical benchmark results from the local CSV storage
 * and writes a pretty-printed ANSI text report to the specified file.
 */
void ExportToAnsiText(const char *filename)
{
    /* Safety check: ensure filename and CSV path are valid */
    if (!filename || filename[0] == '\0')
        return;

    BPTR file = IDOS->FOpen(filename, MODE_NEWFILE, 4096);
    if (!file) {
        LOG_DEBUG("Export: Failed to open %s for writing", filename);
        ShowMessage("AmigaDiskBench Error", "Failed to open destination file\nfor writing.", "OK");
        return;
    }

    /* 1. Header */
    IDOS->FPuts(file, "AmigaDiskBench - Historical Benchmark Report\n");
    IDOS->FPuts(file, "==============================================\n\n");

    /* Attempt to get a date string or just use label */
    IDOS->FPrintf(file, "Generated by AmigaDiskBench %s\n\n", APP_VERSION_STR);

    /* 2. Table Header */
    /* Column widths: Date(10) | Volume(10) | Test(10) | BSize(5) | P(1) | MB/s(7) | IOPS(7) | FS */
    IDOS->FPuts(file, "Date       | Volume     | Test       | BSize | P | MB/s    | IOPS    | FileSystem\n");
    IDOS->FPuts(file, "-----------+------------+------------+-------+-+---------+---------+-----------\n");

    /* 3. Read from CSV and format.
     * We validate ui.csv_path existence here.
     */
    if (ui.csv_path[0] == '\0') {
        IDOS->FPuts(file, "No history CSV path configured.\n");
    } else {
        BPTR csvFile = IDOS->FOpen(ui.csv_path, MODE_OLDFILE, 4096);
        if (csvFile) {
            char line[1024];
            /* Skip header if present */
            IDOS->FGets(csvFile, line, sizeof(line));

            while (IDOS->FGets(csvFile, line, sizeof(line))) {
                char *token;
                char *rest = line;
                char *fields[19];
                int i = 0;

                /* strsep handles empty fields better than strtok.
                 * Current CSV has 19 fields. We read what we need.
                 */
                while ((token = strsep(&rest, ",")) && i < 19) {
                    fields[i++] = token;
                }

                /* Format each row: Date(1), Volume(3), Test(2), BSize(11), P(10), MB/s(5), IOPS(6), FS(4) */
                if (i >= 12) {
                    IDOS->FPrintf(file, "%-10s | %-10s | %-10s | %-5s | %s | %7s | %7s | %s\n",
                                  fields[1],  /* DateTime */
                                  fields[3],  /* Volume */
                                  fields[2],  /* Type */
                                  fields[11], /* BlockSize */
                                  fields[10], /* Passes */
                                  fields[5],  /* MB/s */
                                  fields[6],  /* IOPS */
                                  fields[4]   /* FileSystem */
                    );
                }
            }
            IDOS->FClose(csvFile);
        }
    }

    IDOS->FPuts(file, "\n--- End of Report ---\n");
    IDOS->FClose(file);

    LOG_DEBUG("Export: Successfully saved to %s", filename);

    ShowMessage("AmigaDiskBench", "Export completed successfully.", "OK");
}
